// <auto-generated />
using System;
using IronAndBreath.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IronAndBreath.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914110622_AddExerciseCoachingMetadata")]
    partial class AddExerciseCoachingMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("IronAndBreath.Domain.Entities.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AnimationRef")
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseSets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Benefits")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreathingConcentric")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreathingEccentric")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("BreathingNotes")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("CommonMistakes")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cue")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PrimaryMuscles")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("RepsDisplay")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("SafetyTips")
                        .HasMaxLength(600)
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondaryMuscles")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsHigh")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TargetRepsLow")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Tempo")
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<int?>("VideoId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("VideoId");

                    b.HasIndex("WorkoutDayId", "SortOrder");

                    b.ToTable("Exercises");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseSets = 4,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Lower elbows to the floor, pause, press up.",
                            Name = "Dumbbell Floor Press",
                            PrimaryMuscles = "Chest,Triceps",
                            RepsDisplay = "4 sets x 10-12 reps",
                            SecondaryMuscles = "Shoulders",
                            SortOrder = 1,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 10,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 2,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Brace core, press overhead without arching the back.",
                            Name = "Dumbbell Shoulder Press",
                            PrimaryMuscles = "Shoulders,Triceps",
                            RepsDisplay = "3 sets x 10-12 reps",
                            SecondaryMuscles = "Upper Chest",
                            SortOrder = 2,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 10,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 3,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Soft elbows, wide arc, squeeze the chest at the top.",
                            Name = "Dumbbell Floor Flyes",
                            PrimaryMuscles = "Chest",
                            RepsDisplay = "3 sets x 12-15 reps",
                            SecondaryMuscles = "Shoulders",
                            SortOrder = 3,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 12,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 4,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Straight line head-to-heels, full range of motion.",
                            Name = "Push-ups",
                            PrimaryMuscles = "Chest,Triceps",
                            RepsDisplay = "To near-failure",
                            SecondaryMuscles = "Shoulders,Core",
                            SortOrder = 4,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 5,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Lead with the elbows, raise to shoulder height only.",
                            Name = "Lateral Raises",
                            PrimaryMuscles = "Shoulders",
                            RepsDisplay = "3 sets x 15 reps",
                            SecondaryMuscles = "Traps",
                            SortOrder = 5,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 15,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 6,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Keep elbows tucked, control the negative.",
                            Name = "Tricep Dumbbell Extension",
                            PrimaryMuscles = "Triceps",
                            RepsDisplay = "3 sets x 12-15 reps",
                            SortOrder = 6,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 12,
                            WorkoutDayId = 1
                        },
                        new
                        {
                            Id = 7,
                            BaseSets = 4,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Chest up, sit between the hips, knees track toes.",
                            Name = "Goblet Squat",
                            PrimaryMuscles = "Quadriceps,Glutes",
                            RepsDisplay = "4 sets x 12-15 reps",
                            SecondaryMuscles = "Core,Hamstrings",
                            SortOrder = 1,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 12,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 8,
                            BaseSets = 4,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Hinge at the hips, soft knees, feel the hamstrings.",
                            Name = "Dumbbell Romanian Deadlift",
                            PrimaryMuscles = "Hamstrings,Glutes",
                            RepsDisplay = "4 sets x 12 reps",
                            SecondaryMuscles = "Lower Back",
                            SortOrder = 2,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 12,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 9,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Long stride, back knee toward the floor, torso tall.",
                            Name = "Walking Lunges",
                            PrimaryMuscles = "Quadriceps,Glutes",
                            RepsDisplay = "3 sets x 12 reps/leg",
                            SecondaryMuscles = "Hamstrings,Calves",
                            SortOrder = 3,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 12,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 10,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Full stretch at the bottom, pause at the top.",
                            Name = "Standing Calf Raise",
                            PrimaryMuscles = "Calves",
                            RepsDisplay = "3 sets x 20 reps",
                            SortOrder = 4,
                            TargetRepsHigh = 20,
                            TargetRepsLow = 20,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 11,
                            BaseSets = 3,
                            BreathingNotes = "Breathe slow and steady — don't hold your breath.",
                            Cue = "Squeeze glutes and abs, no sagging hips.",
                            Name = "Plank Hold",
                            PrimaryMuscles = "Core",
                            RepsDisplay = "45-60 sec",
                            SecondaryMuscles = "Shoulders,Glutes",
                            SortOrder = 5,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 12,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Press low back down, lower legs slowly.",
                            Name = "Lying Leg Raises",
                            PrimaryMuscles = "Core",
                            RepsDisplay = "3 sets x 15 reps",
                            SecondaryMuscles = "Hip Flexors",
                            SortOrder = 6,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 15,
                            WorkoutDayId = 2
                        },
                        new
                        {
                            Id = 13,
                            BaseSets = 4,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Flat back, drive elbow to hip, squeeze the lat.",
                            Name = "Single-Arm Dumbbell Row",
                            PrimaryMuscles = "Back,Lats",
                            RepsDisplay = "4 sets x 10-12 reps/side",
                            SecondaryMuscles = "Biceps",
                            SortOrder = 1,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 10,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 14,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Wide feet for stability, minimize hip rotation.",
                            Name = "Renegade Row",
                            PrimaryMuscles = "Back,Core",
                            RepsDisplay = "3 sets x 10 reps/side",
                            SecondaryMuscles = "Biceps,Shoulders",
                            SortOrder = 2,
                            TargetRepsHigh = 10,
                            TargetRepsLow = 10,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 15,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Elbows pinned, no swinging, full squeeze.",
                            Name = "Bicep Curl",
                            PrimaryMuscles = "Biceps",
                            RepsDisplay = "3 sets x 12-15 reps",
                            SecondaryMuscles = "Forearms",
                            SortOrder = 3,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 12,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 16,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Neutral grip, control both directions.",
                            Name = "Hammer Curl",
                            PrimaryMuscles = "Biceps,Forearms",
                            RepsDisplay = "3 sets x 12-15 reps",
                            SortOrder = 4,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 12,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 17,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Hinge forward, raise wide, lead with pinkies.",
                            Name = "Rear Delt Flye",
                            PrimaryMuscles = "Rear Delts",
                            RepsDisplay = "3 sets x 15 reps",
                            SecondaryMuscles = "Traps,Back",
                            SortOrder = 5,
                            TargetRepsHigh = 15,
                            TargetRepsLow = 15,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 18,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Drive elbows down and back, chest to the edge.",
                            Name = "Towel Row Under Table (or Pull-ups)",
                            PrimaryMuscles = "Back,Lats",
                            RepsDisplay = "To near-failure",
                            SecondaryMuscles = "Biceps",
                            SortOrder = 6,
                            WorkoutDayId = 3
                        },
                        new
                        {
                            Id = 19,
                            BaseSets = 4,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Squat, then drive through into the press in one motion.",
                            Name = "Dumbbell Thruster",
                            PrimaryMuscles = "Quadriceps,Shoulders",
                            RepsDisplay = "4 sets x 10-12 reps",
                            SecondaryMuscles = "Glutes,Triceps,Core",
                            SortOrder = 1,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 10,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 20,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Neutral spine, push the floor away, lock out tall.",
                            Name = "Dumbbell Deadlift",
                            PrimaryMuscles = "Hamstrings,Glutes",
                            RepsDisplay = "3 sets x 12 reps",
                            SecondaryMuscles = "Back,Core",
                            SortOrder = 2,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 12,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 21,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Straight line head-to-heels, full range of motion.",
                            Name = "Push-ups",
                            PrimaryMuscles = "Chest,Triceps",
                            RepsDisplay = "To near-failure",
                            SecondaryMuscles = "Shoulders,Core",
                            SortOrder = 3,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 22,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Hinge to ~45 degrees, row to the lower ribs.",
                            Name = "Bent-Over Row",
                            PrimaryMuscles = "Back,Lats",
                            RepsDisplay = "3 sets x 12 reps",
                            SecondaryMuscles = "Biceps,Rear Delts",
                            SortOrder = 4,
                            TargetRepsHigh = 12,
                            TargetRepsLow = 12,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 23,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Rotate from the trunk, touch each side.",
                            Name = "Russian Twist",
                            PrimaryMuscles = "Core,Obliques",
                            RepsDisplay = "3 sets x 20 reps",
                            SecondaryMuscles = "Hip Flexors",
                            SortOrder = 5,
                            TargetRepsHigh = 20,
                            TargetRepsLow = 20,
                            WorkoutDayId = 4
                        },
                        new
                        {
                            Id = 24,
                            BaseSets = 3,
                            BreathingConcentric = "Exhale",
                            BreathingEccentric = "Inhale",
                            Cue = "Opposite elbow to knee, slow and controlled.",
                            Name = "Bicycle Crunch",
                            PrimaryMuscles = "Core,Obliques",
                            RepsDisplay = "3 sets x 20 reps",
                            SecondaryMuscles = "Hip Flexors",
                            SortOrder = 6,
                            TargetRepsHigh = 20,
                            TargetRepsLow = 20,
                            WorkoutDayId = 4
                        });
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.ExerciseVideo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Attribution")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("Provider")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailUrl")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ExerciseVideos");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.ProgramProgressionPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<int>("PhaseNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepsHintText")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("RestBetweenExercisesSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestBetweenSetsSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RestWorkSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetDelta")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekEnd")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WeekStart")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PhaseNumber")
                        .IsUnique();

                    b.ToTable("ProgramProgressionPhases");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Notes = "Focus on slow, controlled tempo and full range of motion.",
                            PhaseNumber = 1,
                            RepsHintText = "10-12 reps, slow controlled tempo",
                            RestBetweenExercisesSeconds = 120,
                            RestBetweenSetsSeconds = 90,
                            RestWorkSeconds = 40,
                            SetDelta = 0,
                            WeekEnd = 4,
                            WeekStart = 1
                        },
                        new
                        {
                            Id = 2,
                            Notes = "Shorter rest. Encourage supersetting where possible.",
                            PhaseNumber = 2,
                            RepsHintText = "15-20 reps, higher volume",
                            RestBetweenExercisesSeconds = 90,
                            RestBetweenSetsSeconds = 60,
                            RestWorkSeconds = 40,
                            SetDelta = 0,
                            WeekEnd = 8,
                            WeekStart = 5
                        },
                        new
                        {
                            Id = 3,
                            Notes = "Pause reps for tension. Optional drop set on the last set of each exercise.",
                            PhaseNumber = 3,
                            RepsHintText = "Add a set, pause reps, shortest rest",
                            RestBetweenExercisesSeconds = 75,
                            RestBetweenSetsSeconds = 45,
                            RestWorkSeconds = 45,
                            SetDelta = 1,
                            WeekEnd = 12,
                            WeekStart = 9
                        });
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.SessionSetLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ExerciseId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RepsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SetNumber")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("WeightKg")
                        .HasPrecision(6, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("WorkoutSessionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutSessionId");

                    b.ToTable("SessionSetLogs");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleSubject")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("GoogleSubject")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.UserProgramSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DaysPerWeekTarget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(4);

                    b.Property<DateOnly>("ProgramStartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProgramSettings");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Focus")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SortOrder");

                    b.HasIndex("UserId");

                    b.ToTable("WorkoutDays");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Focus = "Chest, shoulders, triceps",
                            Name = "Upper Body (Push)",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Focus = "Quads, hamstrings, glutes, core",
                            Name = "Lower Body + Core",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Focus = "Back, biceps, rear delts",
                            Name = "Upper Body (Pull)",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Focus = "Total body, conditioning, core",
                            Name = "Full Body (Metabolic)",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("PhaseNumberAtCompletion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WorkoutDayId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("WorkoutDayId");

                    b.HasIndex("UserId", "Date");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.Exercise", b =>
                {
                    b.HasOne("IronAndBreath.Domain.Entities.ExerciseVideo", "Video")
                        .WithMany("Exercises")
                        .HasForeignKey("VideoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("IronAndBreath.Domain.Entities.WorkoutDay", "WorkoutDay")
                        .WithMany("Exercises")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Video");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.SessionSetLog", b =>
                {
                    b.HasOne("IronAndBreath.Domain.Entities.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("IronAndBreath.Domain.Entities.WorkoutSession", "WorkoutSession")
                        .WithMany("SetLogs")
                        .HasForeignKey("WorkoutSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("WorkoutSession");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.UserProgramSettings", b =>
                {
                    b.HasOne("IronAndBreath.Domain.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutDay", b =>
                {
                    b.HasOne("IronAndBreath.Domain.Entities.User", "User")
                        .WithMany("WorkoutDays")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("User");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutSession", b =>
                {
                    b.HasOne("IronAndBreath.Domain.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IronAndBreath.Domain.Entities.WorkoutDay", "WorkoutDay")
                        .WithMany("Sessions")
                        .HasForeignKey("WorkoutDayId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkoutDay");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.ExerciseVideo", b =>
                {
                    b.Navigation("Exercises");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.User", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("WorkoutDays");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutDay", b =>
                {
                    b.Navigation("Exercises");

                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("IronAndBreath.Domain.Entities.WorkoutSession", b =>
                {
                    b.Navigation("SetLogs");
                });
#pragma warning restore 612, 618
        }
    }
}
